import { amount } from "lib/config";
import { useState } from "react";

import Head from "next/head";
import Heading from "components/Heading";
import prisma from "lib/prisma";
import { getVideos } from "lib/data";
import Videos from "components/Videos";
import LoadMore from "components/LoadMore";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

/** @param {import('next').InferGetServerSidePropsType<typeof getServerSideProps> } props */
export default function Home({ initialVideos }) {
  const router = useRouter();
  const { data: session, status } = useSession();
  const [videos, setVideos] = useState(initialVideos);
  const [reachedEnd, setReachedEnd] = useState(initialVideos.length < amount);

  const loading = status === "loading";
  if (loading) return null;

  if (session && !session.user.name) router.push("/setup");

  return (
    <>
      <Head>
        <title>Youtube-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading />

      <div className="">
        {videos.length === 0 && (
          <p className="flex justify-center mt-20">No Videos found!</p>
        )}
        <Videos videos={videos} />

        {!reachedEnd && (
          <LoadMore
            videos={videos}
            setVideos={setVideos}
            setReachedEnd={setReachedEnd}
          />
        )}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  let videos = await getVideos({}, prisma);
  videos = JSON.parse(JSON.stringify(videos));

  return {
    props: {
      initialVideos: videos,
    },
  };
}
